theme = "catppuccin_mocha"  
[editor]
line-number = "relative"
shell = ["nu", "-c"]
cursorline = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"
  
[editor.statusline]
left = ["mode", "spinner", "selections"]
right = ["diagnostics", "position", "file-encoding",  "file-line-ending", "file-type", "file-name"]
separator = "|" 
mode.normal = "-- NORMAL --"
mode.insert = "-- INSERT --"
mode.select = "-- SELECT --"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1                      

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.z]
d = ["half_page_down", "align_view_center"]
u = ["half_page_up", "align_view_center"]

[keys.normal.Z]
d = ["half_page_down", "align_view_center"]
u = ["half_page_up", "align_view_center"]
